---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: om
  namespace: mongodb
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: om-admin-secret

  configuration:
    # this enables local mode in Ops Manager
    automation.versions.source: local

  statefulSet:
    spec:
      # the Persistent Volume Claim will be created for each Ops Manager Pod
      volumeClaimTemplates:
        - metadata:
            name: mongodb-versions
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - name: mongodb-versions
                  # this is the directory in each Pod where all MongoDB
                  # archives must be put
                  mountPath: /mongodb-ops-manager/mongodb-releases

  # Should match metadata.name
  # in the Kubernetes secret
  # for the admin user
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    members: 3
    # version: 4.2.2-ent
    persistent: true
