---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: om
  namespace: mongodb
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: om-admin-secret
  # Should match metadata.name
  # in the Kubernetes secret
  # for the admin user
  externalConnectivity:
    type: NodePort
  backup:
    enabled: false
  applicationDatabase:
    members: 3
    # version: 4.2.2-ent
    persistent: false
